### ISSUE TITLE
Can't interpret w as a window

### ISSUE THREAD

**Issue by OrangeJ-ui** [ACSoupir/SpatialTranscriptomics_YouTube#1]
Dear Sir, when I run spatialTIME, there is a error "can't interpret w as a window"; I try to load "maptools" to solve the problem, which didnt work.
If you could help me, much appreciation

**Comment by ACSoupir** [comment]
Hey, Zhiyuan.

Were you able to figure out the issue from the YouTube comment? Sounded like there aren't enough cells or points remaining in a sample. Talked to the clinical fellow and was correct in my comment about how he got the same error - some spatial data frame (in the `mIF` object) had 0 rows after he did some filtering.

**Comment by OrangeJ-ui** [comment]
Dear Professor,


Thank you so much for your attention.


Yes,you were right.


The reason is because of lack of data point.
Because I want to save some time for do a little bit trial version on the code.


Thank u so much .
Much appreciated for your time.


Zhiyuan Cheng&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Alex Soupir ***@***.***&gt;
Date: Wed,Mar 20,2024 2:50 PM
To: ACSoupir/SpatialTranscriptomics_YouTube ***@***.***&gt;
Cc: OrangeJ-ui ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ACSoupir/SpatialTranscriptomics_YouTube] Can't interpret w as awindow (Issue #1)





 
Hey, Zhiyuan.
 
Were you able to figure out the issue from the YouTube comment? Sounded like there aren't enough cells or points remaining in a sample. Talked to the clinical fellow and was correct in my comment about how he got the same error - some spatial data frame (in the mIF object) had 0 rows after he did some filtering.
